//User
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//Manager
export const SET_CURRENT_SECTION = "SET_CURRENT_SECTION";
export const SET_CURRENT_ID = "SET_CURRENT_ID";
export const CLEAR_CURRENT_SECTION_AND_ID = "CLEAR_CURRENT_SECTION_AND_ID";
export const SET_EXTRA_ID_INFO = "SET_EXTRA_ID_INFO";

//Messages / Errors
export const SET_MESSAGES = "SET_MESSAGES";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REMOVE_ERROR = "REMOVE_ERROR";

//Teams
export const SET_TEAMS = "SET_TEAMS";
export const SET_TEAM_UPDATED = "SET_TEAM_UPDATED";

//Projects
export const SET_PROJECTS = "SET_PROJECTS";
export const SET_PROJECT_UPDATED = "SET_PROJECT_UPDATED";

//Bugs
export const SET_BUGS = "SET_BUGS";

//Ui
export const SET_LOADING_UI = "SET_LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const SET_SHOW_MODAL = "SET_SHOW_MODAL";
export const SET_CLOSE_MODAL = "SET_CLOSE_MODAL";
export const SET_DELETE_ITEM = "SET_DELETE_ITEM";
export const REMOVE_DELETE_ITEM = "REMOVE_DELETE_ITEM";
export const SET_ITEM_TYPE = "SET_ITEM_TYPE";
export const REMOVE_ITEM_TYPE = "REMOVE_ITEM_TYPE";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const REMOVE_CURRENT_LOCATION = "REMOVE_CURRENT_LOCATION";

//Chat
export const SET_CHATS = "SET_CHATS";
export const RESET_CHATS = "RESET_CHATS";
export const ADD_NEW_CHAT_MESSAGE = "ADD_NEW_CHAT_MESSAGE";
export const SET_CURRENT_CHAT_TEAM_ID = "SET_CURRENT_CHAT_TEAM_ID";
